# Comment blocks have been tried with no luck ;)

#networks:
#  default:
#    name: awesome-network
services:
  db:
    hostname: db  # Oh, god! this took me awhile to figure out
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
#    volumes:
#      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    environment:
      API_KEY: ${API_KEY}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
#      DB_CONNECTION_STRING: postgresql://testuser:testpwd@db:5432/testuser
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2512:2512
    links:
      - "db:database"
  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "alembic"
    command: "alembic upgrade head"
    links:
      - "db:database"
    environment:
      - DB_URL=postgresql://testuser:testpwd@db:5432/testuser
      - DB_CONNECTION_STRING=postgresql://testuser:testpwd@db:5432/testuser
#volumes:
#  db:
#    driver: local
#  db_data:
#  migration:
